server:
  host: 0.0.0.0
  port: 13000
  enable_api_prefix: False
  api_prefix: /api
  workers: 1
  enable_rate_limit: False
  global_default_limits: 10/second

database:
  # sqlite+aiosqlite:///your/absolute/path/xxx.db
  # postgresql+asyncpg://user:pass@localhost:port/dbname
  # mysql+aiomysql://user:pass@localhost:port/dbname
  url: ""
  pool_size: 10
  max_overflow: 20
  pool_recycle: 1800
  echo_sql: True
  pool_pre_ping: True
  enable_redis: False
  cache_host: 127.0.0.1
  cache_port: 6379
  cache_pass: ""
  cache_db_num: 0

security:
  enable: False
  enable_swagger: False
  algorithm: HS256
  secret_key: 43365f0e3e88863ff5080ac382d7717634a8ef72d8f2b52d436fc9847dbecc64
  access_token_expire_minutes: 30
  refresh_token_expire_minutes: 43200
  white_list_routes: /api/v1/probe/liveness, /api/v1/probe/readiness, /api/v1/user/register, /api/v1/auth:signInWithEmailAndPassword,
  backend_cors_origins: http://127.0.0.1:8000, http://localhost:8000, http://localhost
  black_ip_list: ""

log:
  log_dir: "logs"
  log_level: "INFO"
  log_rotation: "1 day"
  log_retention: "30 days"
  log_format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | [{extra[correlation_id]}] | {name}:{function}:{line} | {message}"
  time_format: "YYYY-MM-DD"
  enable_console_log: true
  error_log_rotation: "1 day"
  error_log_retention: "90 days"
  enable_json_logs: false
  enable_async: true
  max_file_size: "100 MB"
